/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;
import javax.swing.JOptionPane;
import proyecto.Camas;
import proyecto.Diagnostico;
import proyecto.PacienteDAO;
import proyecto.PacienteVO;

public class MenuPrincipal extends javax.swing.JFrame {

    PacienteDAO pacienteDAO = new PacienteDAO();
    Camas camas=new Camas();

    
    public MenuPrincipal() {
        initComponents();
        super.setLocationRelativeTo(null);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        panelPaciente = new javax.swing.JPanel();
        panelnfoPersonal = new javax.swing.JPanel();
        txtNumeroDocumentoPaciente = new javax.swing.JLabel();
        fieldNumeroDocumentoPaciente = new javax.swing.JTextField();
        txtTipoDocumentoPaciente = new javax.swing.JLabel();
        boxTipoDocPaciente = new javax.swing.JComboBox<>();
        txtNombrePaciente = new javax.swing.JLabel();
        fieldNombrePaciente = new javax.swing.JTextField();
        txtApellidoPaciente = new javax.swing.JLabel();
        fieldApellidoPaciente = new javax.swing.JTextField();
        txtGeneroPaciente = new javax.swing.JLabel();
        boxGeneroPaciente = new javax.swing.JComboBox<>();
        txtSangrePaciente = new javax.swing.JLabel();
        fieldSangrePaciente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        panelSintomas = new javax.swing.JPanel();
        txtSistemaRepiratorio = new javax.swing.JLabel();
        boxRepiratorios = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        txtCirculatorio = new javax.swing.JLabel();
        txtSistemaDigestivo = new javax.swing.JLabel();
        txtAbdomen = new javax.swing.JLabel();
        boxDigestivos = new javax.swing.JComboBox<>();
        boxGenerales = new javax.swing.JComboBox<>();
        txtSistemaRepiratorio2 = new javax.swing.JLabel();
        btnRegistrarPaciente = new javax.swing.JButton();
        btnMostrarPaciente = new javax.swing.JButton();
        btnEliminarPaciente = new javax.swing.JButton();
        btnModificarPaciente = new javax.swing.JButton();
        txtTituloPaciente = new javax.swing.JLabel();
        txtRegistrarPaciente = new javax.swing.JLabel();
        panelDoctor = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        panelEnfermero = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        fastAndCareful = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        panelPaciente.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N

        panelnfoPersonal.setBackground(new java.awt.Color(235, 245, 251));

        txtNumeroDocumentoPaciente.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        txtNumeroDocumentoPaciente.setText("Numero de documento");

        fieldNumeroDocumentoPaciente.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        fieldNumeroDocumentoPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNumeroDocumentoPacienteActionPerformed(evt);
            }
        });

        txtTipoDocumentoPaciente.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        txtTipoDocumentoPaciente.setText("Tipo de documento");

        boxTipoDocPaciente.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        boxTipoDocPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Tipo Documento", "Cedula", "Tarjeta De Identidad", "Otro" }));

        txtNombrePaciente.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        txtNombrePaciente.setText("Primer nombre");

        fieldNombrePaciente.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        fieldNombrePaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fieldNombrePacienteActionPerformed(evt);
            }
        });

        txtApellidoPaciente.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        txtApellidoPaciente.setText("Primer apellido");

        fieldApellidoPaciente.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N

        txtGeneroPaciente.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        txtGeneroPaciente.setText("Genero");

        boxGeneroPaciente.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        boxGeneroPaciente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione genero", "Masculino\t", "Femenino" }));

        txtSangrePaciente.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        txtSangrePaciente.setText("Tipo de sangre");

        fieldSangrePaciente.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 1, 15)); // NOI18N
        jLabel1.setText("Informacion Personal");

        javax.swing.GroupLayout panelnfoPersonalLayout = new javax.swing.GroupLayout(panelnfoPersonal);
        panelnfoPersonal.setLayout(panelnfoPersonalLayout);
        panelnfoPersonalLayout.setHorizontalGroup(
            panelnfoPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelnfoPersonalLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelnfoPersonalLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(panelnfoPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumeroDocumentoPaciente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtTipoDocumentoPaciente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtNombrePaciente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtApellidoPaciente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtGeneroPaciente, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtSangrePaciente, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelnfoPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(boxTipoDocPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(boxGeneroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldNumeroDocumentoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldApellidoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(fieldSangrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15))
        );
        panelnfoPersonalLayout.setVerticalGroup(
            panelnfoPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelnfoPersonalLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panelnfoPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTipoDocumentoPaciente)
                    .addComponent(boxTipoDocPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelnfoPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNumeroDocumentoPaciente)
                    .addComponent(fieldNumeroDocumentoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelnfoPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombrePaciente)
                    .addComponent(fieldNombrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelnfoPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fieldApellidoPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoPaciente))
                .addGap(15, 15, 15)
                .addGroup(panelnfoPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtGeneroPaciente)
                    .addComponent(boxGeneroPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panelnfoPersonalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtSangrePaciente)
                    .addComponent(fieldSangrePaciente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        panelSintomas.setBackground(new java.awt.Color(235, 245, 251));

        txtSistemaRepiratorio.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        txtSistemaRepiratorio.setText("Sistema respiratorio/");

        boxRepiratorios.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        boxRepiratorios.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Presion arterial", "Taquicardia", "Tos" }));

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 1, 15)); // NOI18N
        jLabel2.setText("Sintomas");

        txtCirculatorio.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        txtCirculatorio.setText("circulatorio");

        txtSistemaDigestivo.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        txtSistemaDigestivo.setText("Sistema digestivo/");

        txtAbdomen.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        txtAbdomen.setText("abdomen");

        boxDigestivos.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        boxDigestivos.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Vomito", "Estreñimiento", "Ruidos intestinales" }));

        boxGenerales.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        boxGenerales.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ninguno", "Fiebre", "Dolor de cabeza", "Cansancio" }));

        txtSistemaRepiratorio2.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        txtSistemaRepiratorio2.setText("Generales");

        javax.swing.GroupLayout panelSintomasLayout = new javax.swing.GroupLayout(panelSintomas);
        panelSintomas.setLayout(panelSintomasLayout);
        panelSintomasLayout.setHorizontalGroup(
            panelSintomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSintomasLayout.createSequentialGroup()
                .addGroup(panelSintomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelSintomasLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(panelSintomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSistemaRepiratorio)
                            .addComponent(txtCirculatorio))
                        .addGap(18, 18, 18)
                        .addComponent(boxRepiratorios, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(panelSintomasLayout.createSequentialGroup()
                        .addGap(181, 181, 181)
                        .addComponent(jLabel2))
                    .addGroup(panelSintomasLayout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(panelSintomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSistemaDigestivo)
                            .addComponent(txtAbdomen)
                            .addComponent(txtSistemaRepiratorio2))
                        .addGap(18, 18, 18)
                        .addGroup(panelSintomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(boxDigestivos, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boxGenerales, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(10, Short.MAX_VALUE))
        );
        panelSintomasLayout.setVerticalGroup(
            panelSintomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelSintomasLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addGroup(panelSintomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxRepiratorios, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSistemaRepiratorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtCirculatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelSintomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxDigestivos, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSistemaDigestivo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtAbdomen, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(panelSintomasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(boxGenerales, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSistemaRepiratorio2))
                .addGap(68, 68, 68))
        );

        btnRegistrarPaciente.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        btnRegistrarPaciente.setText("Registrar Paciente");
        btnRegistrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarPacienteActionPerformed(evt);
            }
        });

        btnMostrarPaciente.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        btnMostrarPaciente.setText("Mostrar Pacientes");
        btnMostrarPaciente.setToolTipText("");
        btnMostrarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPacienteActionPerformed(evt);
            }
        });

        btnEliminarPaciente.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        btnEliminarPaciente.setText("Eliminar Paciente");
        btnEliminarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarPacienteActionPerformed(evt);
            }
        });

        btnModificarPaciente.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        btnModificarPaciente.setText("Modificar Paciente");
        btnModificarPaciente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarPacienteActionPerformed(evt);
            }
        });

        txtTituloPaciente.setFont(new java.awt.Font("OCR A Extended", 1, 28)); // NOI18N
        txtTituloPaciente.setText("PACIENTE");

        txtRegistrarPaciente.setFont(new java.awt.Font("OCR A Extended", 0, 18)); // NOI18N
        txtRegistrarPaciente.setText("Registrar un paciente");

        javax.swing.GroupLayout panelPacienteLayout = new javax.swing.GroupLayout(panelPaciente);
        panelPaciente.setLayout(panelPacienteLayout);
        panelPacienteLayout.setHorizontalGroup(
            panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelPacienteLayout.createSequentialGroup()
                .addGroup(panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelPacienteLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(panelnfoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(panelSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panelPacienteLayout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(btnEliminarPaciente)
                        .addGap(18, 18, 18)
                        .addComponent(btnMostrarPaciente, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnModificarPaciente))
                    .addGroup(panelPacienteLayout.createSequentialGroup()
                        .addGap(408, 408, 408)
                        .addComponent(txtTituloPaciente)))
                .addContainerGap(30, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPacienteLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPacienteLayout.createSequentialGroup()
                        .addComponent(txtRegistrarPaciente)
                        .addGap(350, 350, 350))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPacienteLayout.createSequentialGroup()
                        .addComponent(btnRegistrarPaciente)
                        .addGap(357, 357, 357))))
        );
        panelPacienteLayout.setVerticalGroup(
            panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelPacienteLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(txtTituloPaciente)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtRegistrarPaciente)
                .addGap(24, 24, 24)
                .addGroup(panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelnfoPersonal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(panelSintomas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnRegistrarPaciente)
                .addGap(18, 18, 18)
                .addGroup(panelPacienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarPaciente)
                    .addComponent(btnModificarPaciente)
                    .addComponent(btnEliminarPaciente))
                .addGap(23, 23, 23))
        );

        jTabbedPane1.addTab("Paciente", panelPaciente);

        panelDoctor.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N

        jButton2.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jButton2.setText("Recetar medicamentos");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelDoctorLayout = new javax.swing.GroupLayout(panelDoctor);
        panelDoctor.setLayout(panelDoctorLayout);
        panelDoctorLayout.setHorizontalGroup(
            panelDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelDoctorLayout.createSequentialGroup()
                .addGap(327, 327, 327)
                .addComponent(jButton2)
                .addContainerGap(423, Short.MAX_VALUE))
        );
        panelDoctorLayout.setVerticalGroup(
            panelDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelDoctorLayout.createSequentialGroup()
                .addContainerGap(325, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(133, 133, 133))
        );

        jTabbedPane1.addTab("Doctor(a)", panelDoctor);

        panelEnfermero.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N

        jButton1.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        jButton1.setText("Administrar Camas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelEnfermeroLayout = new javax.swing.GroupLayout(panelEnfermero);
        panelEnfermero.setLayout(panelEnfermeroLayout);
        panelEnfermeroLayout.setHorizontalGroup(
            panelEnfermeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEnfermeroLayout.createSequentialGroup()
                .addGap(301, 301, 301)
                .addComponent(jButton1)
                .addContainerGap(490, Short.MAX_VALUE))
        );
        panelEnfermeroLayout.setVerticalGroup(
            panelEnfermeroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelEnfermeroLayout.createSequentialGroup()
                .addContainerGap(386, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(73, 73, 73))
        );

        jTabbedPane1.addTab("Enfermerx", panelEnfermero);

        fastAndCareful.setFont(new java.awt.Font("Impact", 0, 36)); // NOI18N
        fastAndCareful.setText("FAST AND CAREFUL (F&C)");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(fastAndCareful)
                .addGap(300, 300, 300))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fastAndCareful)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void fieldNumeroDocumentoPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNumeroDocumentoPacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNumeroDocumentoPacienteActionPerformed

    private void fieldNombrePacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fieldNombrePacienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fieldNombrePacienteActionPerformed

    private void btnRegistrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarPacienteActionPerformed
        registrarPaciente();

        fieldNumeroDocumentoPaciente.setText("");
        fieldNombrePaciente.setText("");
        fieldApellidoPaciente.setText("");
        fieldSangrePaciente.setText("");
        boxTipoDocPaciente.setSelectedIndex(0);
        boxGeneroPaciente.setSelectedIndex(0);
        boxRepiratorios.setSelectedIndex(0);
        boxDigestivos.setSelectedIndex(0);
        boxGenerales.setSelectedIndex(0);
    }//GEN-LAST:event_btnRegistrarPacienteActionPerformed

    private void btnMostrarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPacienteActionPerformed
        MostrarPaciente mostrar = new MostrarPaciente(pacienteDAO.getInfoPaciente(), pacienteDAO);
        mostrar.setVisible(true);
    }//GEN-LAST:event_btnMostrarPacienteActionPerformed

    private void btnEliminarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarPacienteActionPerformed
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Ingrese documento del paciente que desea eliminar"));
        pacienteDAO.eliminarPaciente(codigo);
    }//GEN-LAST:event_btnEliminarPacienteActionPerformed

    private void btnModificarPacienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarPacienteActionPerformed
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Ingrese documento del paciente que desea actualizar"));
        pacienteDAO.actualizarPaciente(codigo, pacienteDAO, camas);
    }//GEN-LAST:event_btnModificarPacienteActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            camas.ventanaCamas();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int codigo = Integer.parseInt(JOptionPane.showInputDialog("Ingrese documento del paciente al que desea recetar medicamentos"));
        pacienteDAO.diagnosticarMedicamentos(codigo, pacienteDAO);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxDigestivos;
    private javax.swing.JComboBox<String> boxGenerales;
    private javax.swing.JComboBox<String> boxGeneroPaciente;
    private javax.swing.JComboBox<String> boxRepiratorios;
    private javax.swing.JComboBox<String> boxTipoDocPaciente;
    private javax.swing.JButton btnEliminarPaciente;
    private javax.swing.JButton btnModificarPaciente;
    private javax.swing.JButton btnMostrarPaciente;
    private javax.swing.JButton btnRegistrarPaciente;
    private javax.swing.JLabel fastAndCareful;
    private javax.swing.JTextField fieldApellidoPaciente;
    private javax.swing.JTextField fieldNombrePaciente;
    private javax.swing.JTextField fieldNumeroDocumentoPaciente;
    private javax.swing.JTextField fieldSangrePaciente;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel panelDoctor;
    private javax.swing.JPanel panelEnfermero;
    private javax.swing.JPanel panelPaciente;
    private javax.swing.JPanel panelSintomas;
    private javax.swing.JPanel panelnfoPersonal;
    private javax.swing.JLabel txtAbdomen;
    private javax.swing.JLabel txtApellidoPaciente;
    private javax.swing.JLabel txtCirculatorio;
    private javax.swing.JLabel txtGeneroPaciente;
    private javax.swing.JLabel txtNombrePaciente;
    private javax.swing.JLabel txtNumeroDocumentoPaciente;
    private javax.swing.JLabel txtRegistrarPaciente;
    private javax.swing.JLabel txtSangrePaciente;
    private javax.swing.JLabel txtSistemaDigestivo;
    private javax.swing.JLabel txtSistemaRepiratorio;
    private javax.swing.JLabel txtSistemaRepiratorio2;
    private javax.swing.JLabel txtTipoDocumentoPaciente;
    private javax.swing.JLabel txtTituloPaciente;
    // End of variables declaration//GEN-END:variables


 private void registrarPaciente() {
        PacienteVO pacienteVO = new PacienteVO();
        pacienteVO.setNumeroID(Integer.parseInt(fieldNumeroDocumentoPaciente.getText()));
        pacienteVO.setTipoID((String) boxTipoDocPaciente.getSelectedItem());
        pacienteVO.setNombre(fieldNombrePaciente.getText());
        pacienteVO.setApellido(fieldApellidoPaciente.getText());
        pacienteVO.setGenero((String) boxGeneroPaciente.getSelectedItem());
        pacienteVO.setTipoSangre(fieldSangrePaciente.getText());

        pacienteVO.setSintomaRespiratorio((String) boxRepiratorios.getSelectedItem());
        pacienteVO.setSintomaDigestivo((String) boxDigestivos.getSelectedItem());
        pacienteVO.setSintomaGeneral((String) boxGenerales.getSelectedItem());

        pacienteDAO.registrarPaciente(pacienteVO);

        Diagnostico diagnostico = new Diagnostico();
        diagnostico.dianosticarPaciente(pacienteVO);
        diagnostico.asignarCama(camas);
        

    }



}
