/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import java.util.Enumeration;
import java.util.Hashtable;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import proyecto.PacienteDAO;
import proyecto.PacienteVO;

/**
 *
 * @author HOME
 */
public class MostrarPaciente extends javax.swing.JFrame {

    /**
     * Creates new form MostrarPaciente
     */
    public MostrarPaciente(Hashtable<Integer, PacienteVO> infoPaciente, PacienteDAO pacienteDAO) {
        initComponents(); 
        llenarTabla(infoPaciente);
        
        super.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tablaPacientes = new javax.swing.JTable();
        btnCerrarventana = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tablaPacientes.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        tablaPacientes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Tipo Documento", "Numero Documento", "Nombre", "Apellido", "Genero", "Tipo De Sangre ", "Sintoma 1", "Sintoma 2", "Sintoma 3", "Enfermedad", "Triage", "Medicamento 1", "Medicamento 2", "Medicamento 3"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaPacientes);
        if (tablaPacientes.getColumnModel().getColumnCount() > 0) {
            tablaPacientes.getColumnModel().getColumn(0).setResizable(false);
            tablaPacientes.getColumnModel().getColumn(0).setPreferredWidth(160);
            tablaPacientes.getColumnModel().getColumn(1).setResizable(false);
            tablaPacientes.getColumnModel().getColumn(2).setResizable(false);
            tablaPacientes.getColumnModel().getColumn(3).setResizable(false);
            tablaPacientes.getColumnModel().getColumn(4).setResizable(false);
            tablaPacientes.getColumnModel().getColumn(5).setResizable(false);
            tablaPacientes.getColumnModel().getColumn(6).setResizable(false);
            tablaPacientes.getColumnModel().getColumn(7).setResizable(false);
            tablaPacientes.getColumnModel().getColumn(8).setResizable(false);
            tablaPacientes.getColumnModel().getColumn(9).setResizable(false);
            tablaPacientes.getColumnModel().getColumn(10).setResizable(false);
            tablaPacientes.getColumnModel().getColumn(11).setResizable(false);
            tablaPacientes.getColumnModel().getColumn(12).setResizable(false);
            tablaPacientes.getColumnModel().getColumn(13).setResizable(false);
        }

        btnCerrarventana.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        btnCerrarventana.setText("Cerrar Ventana");
        btnCerrarventana.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarventanaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 924, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCerrarventana)
                .addGap(369, 369, 369))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnCerrarventana)
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarventanaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarventanaActionPerformed
        super.dispose();
    }//GEN-LAST:event_btnCerrarventanaActionPerformed

    public void llenarTabla(Hashtable<Integer, PacienteVO> infoPaciente) {
        
        DefaultTableModel mt = new DefaultTableModel(new String[]{"Tipo Documento", "Numero Documento", "Nombre","Apellido","Genero",
            "Tipo De Sangre","Sintoma 1", "Sintoma 2", "Sintoma 3","Enfermedad", "Triage","Medicamento 1", "Medicamento 2",
        "Medicamento 3"}, infoPaciente.size());

        
        
        tablaPacientes.setModel(mt);
        
        
        
         Enumeration <PacienteVO> Pacientes = infoPaciente.elements();
        
        TableModel modeloDatos = tablaPacientes.getModel();
        for (int i = 0; i < infoPaciente.size(); i++) {
            PacienteVO e = Pacientes.nextElement();
            modeloDatos.setValueAt(e.getTipoID(), i, 0);
            modeloDatos.setValueAt( e.getNumeroID(), i, 1);
            modeloDatos.setValueAt( e.getNombre(), i, 2);
            modeloDatos.setValueAt( e.getApellido(), i, 3);
            modeloDatos.setValueAt(e.getGenero(), i, 4);
            modeloDatos.setValueAt(e.getTipoSangre(), i, 5);
            modeloDatos.setValueAt(e.getSintomaRespiratorio(), i, 6);
            modeloDatos.setValueAt(e.getSintomaDigestivo(), i, 7);
            modeloDatos.setValueAt(e.getSintomaGeneral(), i, 8);
            modeloDatos.setValueAt(e.getEnfermedad(), i, 9);
            modeloDatos.setValueAt(e.getTriage(), i, 10);
            modeloDatos.setValueAt(e.getMedicamento1(), i, 11);
            modeloDatos.setValueAt(e.getMedicamento2(), i, 12);
            modeloDatos.setValueAt(e.getMedicamento3(), i, 13);
            
        }
        
        
        
         
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCerrarventana;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaPacientes;
    // End of variables declaration//GEN-END:variables
}
