/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Presentacion;

import proyecto.PacienteVO;

/**
 *
 * @author HOME
 */
public class MostrarFactura extends javax.swing.JFrame {

    /**
     * Creates new form MostrarFactura
     */
    public MostrarFactura(PacienteVO pacienteVO, int totalMedicamento1, int totalMedicamento2, int totalMedicamento3, 
            int total, int precioCama) {
        initComponents();
        super.setLocationRelativeTo(null);
        llenarFactura(pacienteVO, totalMedicamento1, totalMedicamento2, totalMedicamento3, total, precioCama);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0));
        labelNombre = new javax.swing.JLabel();
        fastAndCareful = new javax.swing.JLabel();
        labelNumeroDocumento = new javax.swing.JLabel();
        panel1 = new java.awt.Panel();
        txtPrecio = new javax.swing.JLabel();
        txtDescripcion1 = new javax.swing.JLabel();
        Total = new javax.swing.JLabel();
        txtPrecio2 = new javax.swing.JLabel();
        labelMedicamento1 = new javax.swing.JLabel();
        labelPrecio1 = new javax.swing.JLabel();
        labelCantidad1 = new javax.swing.JLabel();
        labelTotalMedicamento1 = new javax.swing.JLabel();
        labelMedicamento2 = new javax.swing.JLabel();
        labelCantidad2 = new javax.swing.JLabel();
        labelPrecio2 = new javax.swing.JLabel();
        labelTotalMedicamento2 = new javax.swing.JLabel();
        labelMedicamento3 = new javax.swing.JLabel();
        txtCama = new javax.swing.JLabel();
        labelCantidad3 = new javax.swing.JLabel();
        labelPrecio3 = new javax.swing.JLabel();
        labelPrecioCama = new javax.swing.JLabel();
        labelTotalCama = new javax.swing.JLabel();
        labelTotalMedicamento3 = new javax.swing.JLabel();
        panel2 = new java.awt.Panel();
        txtPrecio3 = new javax.swing.JLabel();
        labelTotal = new javax.swing.JLabel();
        fastAndCareful1 = new javax.swing.JLabel();
        btnCerrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labelNombre.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        labelNombre.setText("jLabel1");

        fastAndCareful.setFont(new java.awt.Font("Impact", 0, 24)); // NOI18N
        fastAndCareful.setText("FACTURA");

        labelNumeroDocumento.setFont(new java.awt.Font("OCR A Extended", 0, 13)); // NOI18N
        labelNumeroDocumento.setText("jLabel1");

        panel1.setBackground(new java.awt.Color(235, 245, 251));

        javax.swing.GroupLayout panel1Layout = new javax.swing.GroupLayout(panel1);
        panel1.setLayout(panel1Layout);
        panel1Layout.setHorizontalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel1Layout.setVerticalGroup(
            panel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        txtPrecio.setFont(new java.awt.Font("OCR A Extended", 3, 18)); // NOI18N
        txtPrecio.setText("Precio");

        txtDescripcion1.setFont(new java.awt.Font("OCR A Extended", 3, 18)); // NOI18N
        txtDescripcion1.setText("Descripcion");

        Total.setFont(new java.awt.Font("OCR A Extended", 3, 18)); // NOI18N
        Total.setText("Total a pagar");

        txtPrecio2.setFont(new java.awt.Font("OCR A Extended", 3, 18)); // NOI18N
        txtPrecio2.setText("Cantidad");

        labelMedicamento1.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        labelMedicamento1.setText("Descripcion");

        labelPrecio1.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        labelPrecio1.setText("Descripcion");

        labelCantidad1.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        labelCantidad1.setText("Descripcion");

        labelTotalMedicamento1.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        labelTotalMedicamento1.setText("Descripcion");

        labelMedicamento2.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        labelMedicamento2.setText("Descripcion");

        labelCantidad2.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        labelCantidad2.setText("Descripcion");

        labelPrecio2.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        labelPrecio2.setText("Descripcion");

        labelTotalMedicamento2.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        labelTotalMedicamento2.setText("Descripcion");

        labelMedicamento3.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        labelMedicamento3.setText("Descripcion");

        txtCama.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        txtCama.setText("Cama");

        labelCantidad3.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        labelCantidad3.setText("Descripcion");

        labelPrecio3.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        labelPrecio3.setText("Descripcion");

        labelPrecioCama.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        labelPrecioCama.setText("Descripcion");

        labelTotalCama.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        labelTotalCama.setText("Descripcion");

        labelTotalMedicamento3.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        labelTotalMedicamento3.setText("Descripcion");

        panel2.setBackground(new java.awt.Color(235, 245, 251));

        javax.swing.GroupLayout panel2Layout = new javax.swing.GroupLayout(panel2);
        panel2.setLayout(panel2Layout);
        panel2Layout.setHorizontalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        panel2Layout.setVerticalGroup(
            panel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 10, Short.MAX_VALUE)
        );

        txtPrecio3.setFont(new java.awt.Font("OCR A Extended", 3, 18)); // NOI18N
        txtPrecio3.setText("Total");

        labelTotal.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        labelTotal.setText("Descripcion");

        fastAndCareful1.setFont(new java.awt.Font("Impact", 0, 30)); // NOI18N
        fastAndCareful1.setText("FAST AND CAREFUL (F&C)");

        btnCerrar.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        btnCerrar.setText("Cerrar");
        btnCerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCerrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnCerrar)
                        .addGap(105, 105, 105)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelTotal)
                            .addComponent(Total)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(21, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelNombre)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(labelNumeroDocumento)
                                .addComponent(panel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(txtDescripcion1)
                                        .addComponent(labelMedicamento1)
                                        .addComponent(labelMedicamento2)
                                        .addComponent(labelMedicamento3)
                                        .addComponent(txtCama))
                                    .addGap(45, 45, 45)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelCantidad2)
                                        .addComponent(txtPrecio2)
                                        .addComponent(labelCantidad1)
                                        .addComponent(labelCantidad3))
                                    .addGap(34, 34, 34)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelPrecioCama)
                                        .addComponent(labelPrecio3)
                                        .addComponent(labelPrecio2)
                                        .addComponent(txtPrecio)
                                        .addComponent(labelPrecio1))
                                    .addGap(62, 62, 62)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(labelTotalCama)
                                        .addComponent(labelTotalMedicamento3)
                                        .addComponent(labelTotalMedicamento2)
                                        .addComponent(labelTotalMedicamento1)
                                        .addComponent(txtPrecio3)))
                                .addComponent(panel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(fastAndCareful)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(fastAndCareful1)
                                    .addGap(21, 21, 21))))))
                .addContainerGap(23, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(fastAndCareful)
                    .addComponent(fastAndCareful1))
                .addGap(18, 18, 18)
                .addComponent(labelNombre)
                .addGap(7, 7, 7)
                .addComponent(labelNumeroDocumento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(labelPrecio3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(labelPrecioCama))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtPrecio)
                            .addComponent(txtDescripcion1)
                            .addComponent(txtPrecio2)
                            .addComponent(txtPrecio3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPrecio1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelMedicamento1)
                                .addComponent(labelCantidad1)
                                .addComponent(labelTotalMedicamento1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelPrecio2)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelMedicamento2)
                                .addComponent(labelCantidad2)
                                .addComponent(labelTotalMedicamento2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCantidad3)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(labelTotalMedicamento3)
                                .addComponent(labelMedicamento3)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labelTotalCama)
                            .addComponent(txtCama))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(Total)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(labelTotal)
                        .addContainerGap(27, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCerrar)
                        .addContainerGap())))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCerrarActionPerformed
        super.dispose();
    }//GEN-LAST:event_btnCerrarActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Total;
    private javax.swing.JButton btnCerrar;
    private javax.swing.JLabel fastAndCareful;
    private javax.swing.JLabel fastAndCareful1;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel labelCantidad1;
    private javax.swing.JLabel labelCantidad2;
    private javax.swing.JLabel labelCantidad3;
    private javax.swing.JLabel labelMedicamento1;
    private javax.swing.JLabel labelMedicamento2;
    private javax.swing.JLabel labelMedicamento3;
    private javax.swing.JLabel labelNombre;
    private javax.swing.JLabel labelNumeroDocumento;
    private javax.swing.JLabel labelPrecio1;
    private javax.swing.JLabel labelPrecio2;
    private javax.swing.JLabel labelPrecio3;
    private javax.swing.JLabel labelPrecioCama;
    private javax.swing.JLabel labelTotal;
    private javax.swing.JLabel labelTotalCama;
    private javax.swing.JLabel labelTotalMedicamento1;
    private javax.swing.JLabel labelTotalMedicamento2;
    private javax.swing.JLabel labelTotalMedicamento3;
    private java.awt.Panel panel1;
    private java.awt.Panel panel2;
    private javax.swing.JLabel txtCama;
    private javax.swing.JLabel txtDescripcion1;
    private javax.swing.JLabel txtPrecio;
    private javax.swing.JLabel txtPrecio2;
    private javax.swing.JLabel txtPrecio3;
    // End of variables declaration//GEN-END:variables

    private void llenarFactura(PacienteVO pacienteVO, int totalMedicamento1, int totalMedicamento2, int totalMedicamento3, int total, int precioCama) {
        labelNombre.setText(pacienteVO.getNombre()+" "+pacienteVO.getApellido());
        labelNumeroDocumento.setText(Integer.toString(pacienteVO.getNumeroID()));
        
        
        labelMedicamento1.setText(pacienteVO.getMedicamento1());
        labelMedicamento2.setText(pacienteVO.getMedicamento2());
        labelMedicamento3.setText(pacienteVO.getMedicamento3());
        
        labelCantidad1.setText(Integer.toString(pacienteVO.getCantidadMedicamento1()));
        labelCantidad2.setText(Integer.toString(pacienteVO.getCantidadMedicamento2()));
        labelCantidad3.setText(Integer.toString(pacienteVO.getCantidadMedicamento3()));
        
        labelPrecio1.setText(Integer.toString(pacienteVO.getPrecioMedicamento1()));
        labelPrecio2.setText(Integer.toString(pacienteVO.getPrecioMedicamento2()));
        labelPrecio3.setText(Integer.toString(pacienteVO.getPrecioMedicamento3()));
        
        labelTotalMedicamento1.setText(Integer.toString(totalMedicamento1));
        labelTotalMedicamento2.setText(Integer.toString(totalMedicamento2));
        labelTotalMedicamento3.setText(Integer.toString(totalMedicamento3));
        
        labelPrecioCama.setText(Integer.toString(precioCama));
        labelTotalCama.setText(Integer.toString(precioCama));
        
        labelTotal.setText(Integer.toString(total));
        
        
    }
}
